# Generated by Django 4.2 on 2023-04-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.TextField(default=123, max_length=550, verbose_name='Описание задания'),
            preserve_default=False,
        ),
    ]
